import type {Metadata} from "next";
import "./globals.css";
import { ReactNode } from "react";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children,}: Readonly<{ children: ReactNode; }>) {
    return (
        <html lang="en">
        <head>
        <script src="https://telegram.org/js/telegram-web-app.js?59">
        </script>
        </head>
        <body>
        {children}
        </body>
        </html>
    );
}
